# Generated by Django 4.2.2 on 2023-06-16 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
        ('medical', '0001_initial'),
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='life_experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_life_experience', to='story.story'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='status_conditions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_status_conditions', to='medical.medical'),
        ),
    ]
