# Generated by Django 4.2.2 on 2023-06-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_of_birth', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('number_of_siblings', models.IntegerField()),
                ('number_of_children', models.IntegerField()),
                ('number_of_grandchildren', models.IntegerField()),
                ('biography', models.TextField(max_length=999)),
            ],
        ),
    ]
