# Generated by Django 4.2.2 on 2023-06-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_remove_story_number_of_children_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='education',
            field=models.TextField(max_length=999),
        ),
    ]
